### PR TITLE
Use google to always get the correct font format

### PR DESCRIPTION
**Pull request by mrpikachu**
It seemed as though the ttf was either corrupt or some browsers weren't able to parse it properly.

### CODE REVIEW

**Comment by gipsy-king** [comment]
Could we just copy the whole thing in http://fonts.gstatic.com/s/lato/v11/H2DMvhDLycM56KNuAtbJYA.woff2 and the file itself? I'd rather not depend on a google service.

**Comment by mrpikachu** [comment]
Ya, from what I can see the woff2 file should work. Why are you against google? The txapu site going down is more likely than google being unavailable. On the off chance it isn't up, the font will back up to arial.

**Comment by gipsy-king** [comment]
It's the google font service that might change, and I'm also not a fan of google spying any more than it already does with ads etc. And it should be easy to rip the file off the service.

If you're not in the mood, just tell me and I'll merge this then fix this sometime later :)

**Comment by gipsy-king** [comment]
Oh and thanks! Sorry for not being clear the first time :/

**Comment by mrpikachu** [comment]
No it's fine, I'd rather the site work than having to do workarounds. Give me 2 secs I have to setup git on this computer.

**Pull request closed without merging**
