### PR TITLE
Add Aytos Claims Please.

### PR DESCRIPTION
**Pull request by MagicalMonkey**
Hope I did this right. Let me know if not.

This version uses a different colour to the last cancelled pull request.

Thanks,

Monkey.

### CODE REVIEW

**Comment by hlprimm** [comment]
This does not have a lot of existing claims. It looks like you forked this repository sometime in May or June.

**Comment by hlprimm** [comment]
@MagicalMonkey I am adding your claims to my map so it'll be one perfect pull request. Are there any other colors I can make Aytos? The current map has Dirty_zebra's islands with a very similar color. 

See below. 
https://github.com/gipsy-king/civmap-client/issues/48

That issue uses this map: http://txapu.com/?svg=http://imgh.us/claims_bg.svg

As you can see, the orange you guys chose is oddly similar!!

**Comment by MagicalMonkey** [comment]
Ah damn. I did a git pull thinking it updated the fork but that doesn't do it, does it...

Yeah, use any colour you like. As long as it doesn't clash with anything else I don't mind. I would suggest extremely pink but that's taken, sadly.

**Comment by hlprimm** [comment]
You can close this, see https://github.com/gipsy-king/civmap-client/issues/51

**Comment by MagicalMonkey** [comment]
Thanks!

**Pull request closed without merging**
