### PR TITLE
Update claims.svg

### PR DESCRIPTION
**Pull request by koentinius**
Adding Prussian claims

### CODE REVIEW

**Comment by gipsy-king** [comment]
There are some minor problems with some irrelevant data added to the SVG, but overall **it is a good merge** for standards. I have to edit this manually to remove the unwanted tags and changes, then it's good.

**Comment by hlprimm** [comment]
@gipsy-king I can redo this if you want and just merge it into my own.

**Comment by gipsy-king** [comment]
Ah, I have been busy with RB lately. @hlprimm do you have pending additions?

**Comment by hlprimm** [comment]
@gipsy-king Yeah, I sent as an issue instead. Let me add his claims to the map and get you a single map to upload.

**Comment by hlprimm** [comment]
You can close this. See https://github.com/gipsy-king/civmap-client/issues/51

**Comment by gipsy-king** [comment]
thank you @hlprimm

**Pull request closed without merging**
