### PR TITLE
Carson

### PR DESCRIPTION
**Pull request by ribagi**
Added Carson as a purple.

Hopefully this doesn't break anything. ;)

### CODE REVIEW

**Comment by gipsy-king** [comment]
fixed it, next time please save as plain svg, provide both files and trace land in the same style as the other land claims.

**Comment by staygroovy57** [comment]
There are some claims from Carson for several islands in the -/+ which have never been, and currently are not theirs. Please amend to respect this.

http://i.imgur.com/4feoQff.jpg

**Comment by ribagi** [comment]
Yea, it was a miscommunication between me and someone else. 

Also, sorry for the formatting issues.

**Comment by Rekvia** [comment]
I would also like to add while the subject of claims are up that the desert island is also not a part of Carson. I am referring to the [island here](http://i.imgur.com/pZIeBjj.png) with a half mushroom half green island directly south. This island has been claimed for a while now and can be seen claim in this [two month old map](https://i.imgur.com/RzHB617.jpg)

**Pull request closed without merging**
