### PR TITLE
The Lands of Mir Land Claims

### PR DESCRIPTION
**Pull request by boredarmor**
Hopefully this is all correct. Might be a little on the detailed side.

### CODE REVIEW

**Comment by gipsy-king** [comment]
The merge is good, there is no irrelevant data. But I'd like to retouch the drawing so that its sharpness  matches the other claims, also the borders shouldn't be curved except for perfect arcs in some cases.

**Comment by boredarmor** [comment]
Sure, so when you say "I'd like to..",  would you like me to ? :smiley:

**Comment by gipsy-king** [comment]
If you can do it in the style of the other claims, then yes! Thank you!

**Comment by gipsy-king** [comment]
in inscape I think you can just select all the relevant node and click the "make edges sharp" button.

**Comment by boredarmor** [comment]
Ok, hopefully improved it maybe ?  might have dicked up the merge though.

**Comment by gipsy-king** [comment]
manually merged now

**Pull request closed without merging**
