### PR TITLE
Lots of cities and claims

### PR DESCRIPTION
**Pull request by RailsDev42**
Thanks.

### CODE REVIEW

**Comment by RailsDev42** [comment]
I FUBAR'd my previous pull requests. This should fix it all.

Thanks.

**Comment by gipsy-king** [comment]
Great job! I should be able to upload this tonight.

**Comment by gipsy-king** [comment]
@RailsDev42 you can auto-close issues from commits, adding "closes #123" in the commit message. They will then be closed when the PR is merged :dancer:

**Comment by RailsDev42** [comment]
Excellent, thanks @gipsy-king ! I'll try and use that 'closes' thing from now on then. Looking forward to seeing the map updated. I'm getting together as much as I can to get it up to date.

**Pull request merged**
